### ISSUE TITLE
ajax 异步获取list后_dragId字段不存在，拖拽过程失效

### ISSUE THREAD

**Issue by HAOGRE** [xiongcaihu/vue-power-drag#1]
_dragId:int,//这个是在此组件初始化时附加的临时变量，代表当前对象所在yourList中的下标值（请勿传入相同字段
![image](https://user-images.githubusercontent.com/8871124/28006676-e78c952a-6582-11e7-9a3e-dbe4803ab791.png)

**Comment by xiongcaihu** [comment]
稍等，我回家后查看此问题。

**Comment by xiongcaihu** [comment]
你好，问题已经修复了，麻烦重新npm install vue-power-drag@0.1.9（当前最新的是0.1.9版本，请仔细检查下） 然后重新编译一下，如果没见效，可以再尝试清空浏览器缓存试试。

**Comment by HAOGRE** [comment]
@xiongcaihu 还是很感谢，已经自己找到了源码并修改了！ 不过还是很感谢
