### ISSUE TITLE
快速拉伸或是缩小的时候，chart图表不能自适应

### ISSUE THREAD

**Issue by hduhdc** [xiongcaihu/vue-power-drag#10]
感谢你的开源很有用，但是我发现个问题就是，在快速拉伸的时候chart图表不能自适应。
我尝试加了一个定时器
   setTimeout(() => {
        this.chartInstanceBox["chart" + index].resize();
      }, 100);
确实就好了，有没有合适的方案？？

**Comment by xiongcaihu** [comment]
合适的方案，就是自己自行做适配，echart,highchart都有这个问题，初始化的时候高度宽度是指定值，那么你外框容器size改变时，就需要调用这个chart的实例的resize方法或者reflow什么方法来重新渲染一下。这个不应该框架来适配你的业务，不然就变成业务组件了。
