### ISSUE TITLE
非模块化解决方案

### ISSUE THREAD

**Issue by SheSmileAtme** [xiongcaihu/vue-power-drag#2]
有没有非模块化的使用案例呢？ 让我直接引入js就能使用。

**Comment by xiongcaihu** [comment]
不好意思，当时做的时候没有考虑非模块化的，而又因为我现在在出差，所以等我周一的时候来帮你解决，给您带来不便非常抱歉。

**Comment by xiongcaihu** [comment]
你好，解决方案出来了，在 xiongcaihu/vue-power-drag/singleExample 下，希望能帮你解决问题。
