### ISSUE TITLE
有个严重问题 当拖动元素里面有个div元素或者其他元素 这个拖动就失效了

### ISSUE THREAD

**Issue by 617450941** [xiongcaihu/vue-power-drag#3]
有个严重问题 当拖动元素里面有个div元素或者其他元素 这个拖动就失效了

**Comment by 617450941** [comment]
http://wxyx.lyfz.net/Public/1.png  问题截图

**Comment by xiongcaihu** [comment]
不好意思，这两天一直有约，没时间看电脑。

今天看了一下您提的问题，根本原因可能是我文档没写清楚吧。

针对此问题，我的回答如下：
1、vue-power-drag默认以每个方格的.item元素作为可拖动对象（为什么这么设计呢？因为有时候可能会需要操作里面的内容，如果做了方格内全部元素都能拖动，那么就会有问题，很典型的一个例子就是“highchart应用”）
2、如果需要单独让鼠标按住某一个元素就能拖动整个方格，那么可以给那个元素加上.dragHandle类名。

![image 1](https://user-images.githubusercontent.com/10113078/30526223-809f6d08-9c49-11e7-97b5-f8ad3b90beab.png)

**Comment by xiongcaihu** [comment]
我已更新文档，可查阅。

**Comment by xiongcaihu** [comment]
close
