### ISSUE TITLE
隐藏右下角的箭头

### ISSUE THREAD

**Issue by zhouboluo** [xiongcaihu/vue-power-drag#4]
如题，鼠标悬浮在右下角的时候再显示，这样效果会好一些。

**Comment by xiongcaihu** [comment]
这个可以个人去设置，思路：
首先找到这个右下角的箭头，然后覆盖样式如：opacity:0，
然后再加上拖动框鼠标悬浮后给右下角的箭头设置opacity:1即可。

或者js控制，方法很多。
