### ISSUE TITLE
示例template slot不生效 drag组件包裹元素为空

### ISSUE THREAD

**Issue by mrKylinZhou** [xiongcaihu/vue-power-drag#6]
vue init 一个新的vue项目
npm install vue-power-drag --save

将示例代码粘贴到vue 项目中App.vue 里面 打开页面什么都没有 审查元素 发现vuePowerDrag 没有孩子节点

**Comment by XinHuaLuFang** [comment]
[源码中](https://github.com/xiongcaihu/vue-power-drag/blob/master/src/components/drag/drag.vue#L6)，使用了具名slot，只有slot name匹配上了才会渲染出来，不匹配的直接丢弃了。

作者这里是在每个框中都把list循环了一遍，每个框只会取slot name相同的list child，其他丢弃。

这里应该使用[作用域插槽](https://cn.vuejs.org/v2/guide/components-slots.html#%E4%BD%9C%E7%94%A8%E5%9F%9F%E6%8F%92%E6%A7%BD)好一些。

**Comment by xiongcaihu** [comment]
> [源码中](https://github.com/xiongcaihu/vue-power-drag/blob/master/src/components/drag/drag.vue#L6)，使用了具名slot，只有slot name匹配上了才会渲染出来，不匹配的直接丢弃了。
> 
> 作者这里是在每个框中都把list循环了一遍，每个框只会取slot name相同的list child，其他丢弃。
> 
> 这里应该使用[作用域插槽](https://cn.vuejs.org/v2/guide/components-slots.html#%E4%BD%9C%E7%94%A8%E5%9F%9F%E6%8F%92%E6%A7%BD)好一些。

thanks for your reply, i will optimize as soon as possible.

**Comment by ctuu** [comment]
> [源码中](https://github.com/xiongcaihu/vue-power-drag/blob/master/src/components/drag/drag.vue#L6)，使用了具名slot，只有slot name匹配上了才会渲染出来，不匹配的直接丢弃了。
> 
> 作者这里是在每个框中都把list循环了一遍，每个框只会取slot name相同的list child，其他丢弃。
> 
> 这里应该使用[作用域插槽](https://cn.vuejs.org/v2/guide/components-slots.html#%E4%BD%9C%E7%94%A8%E5%9F%9F%E6%8F%92%E6%A7%BD)好一些。

非也，是需要手动调用组件的 init 方法才能生效（用 $refs 调用)。
