### ISSUE TITLE
不同的屏幕分辨率下,显示问题

### ISSUE THREAD

**Issue by Carolineliu** [xiongcaihu/vue-power-drag#7]
在不同的屏幕分辨率下,修改你的baseWidth,baseHeight,baseMarginLeft,baseMarginTop，把这些值设为20，20，4，4的时候，他就会超出屏幕范围

**Comment by xiongcaihu** [comment]
> 在不同的屏幕分辨率下,修改你的baseWidth,baseHeight,baseMarginLeft,baseMarginTop，把这些值设为20，20，4，4的时候，他就会超出屏幕范围

在src/test.vue里的102行，有适应各种分辨率的方法。
