### ISSUE TITLE
自适应布局

### ISSUE THREAD

**Issue by heyouquan** [xiongcaihu/vue-power-drag#8]
想问一下，如果新增或者删除后怎么实现自适应布局？

**Comment by xiongcaihu** [comment]
画布的宽度一开始是固定的，那么里面每一个拖动的元素大小都不会改变画布的宽度。而如果要做自适应，那么可以动态调整画布的宽度，然后重新init。

**Comment by heyouquan** [comment]
每个单元格如果设定sizex和sizey后，就会固定了宽度，想问一下可以自适应显示吗?

**Comment by xiongcaihu** [comment]
> 每个单元格如果设定sizex和sizey后，就会固定了宽度，想问一下可以自适应显示吗?

你说的意思应该是：假如你在1024*768的屏幕上做好了当前的画布的宽度调整，然后效果满意。
但是放在1688*900的分辨率下或者800*600的分辨率下就会有问题了是吧？

这个就是各个屏幕的适配方法，这个在src/test.vue的102行里有。可以参考
